# Generated by Django 3.0.8 on 2020-07-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='id_proof',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
