# Generated by Django 3.0.8 on 2020-07-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20200730_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='Phone_no',
            field=models.IntegerField(default=91, max_length=10),
        ),
    ]
