# Generated by Django 3.0.8 on 2020-07-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_auto_20200730_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='Phone_no',
            field=models.IntegerField(default=91),
        ),
        migrations.AlterField(
            model_name='host',
            name='email_id',
            field=models.EmailField(default='', max_length=200, unique=True),
        ),
    ]
