# Generated by Django 3.0.8 on 2020-07-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_auto_20200730_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='email_id',
            field=models.EmailField(default='', max_length=200),
        ),
    ]
